// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "starting screen":return img`
ffffffffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
f1ffffffffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffff
ff11ffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffff
ffff1ffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffff
fffff1ff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffffffffff
ffffff11f1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffff1fffffffffffffffff
ffff11ffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111111111111111ffffffffffffffffff
fff11fffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffff1fffffffffffffffffff
ffff1fffffffffffffffffaaaaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffaaaaffffffffffffffffffffffffff1ffff1ffffffffffffffffffff
fff1fffffffff11111111111111fffffffff11111111111111ffffffffffffffff1111111ffffffffffffffffffffffffffffffaaaaaaffffffffffffffffffffffffff1ff1fffffffffffffffffffff
fff1fffffffff1fffffffaa11aaffaaffff1ffffffffffffff1ffffffff1111111fffffffffffff1fffffffffffffffffffffffaaaaaaffaafffffffffffffffffffffff111fffffffffffffffffffff
ff1ffffffffff1ffffaaaaaaa11faaaaaff1ffffffffffffff1fffffff1ffffffffffffff1fffff1ffffffffffffffffff11111111111faaaaaffffffffffffff1fffffff11fffffffffffffffffffff
f1fffffffffff1fffaaaaaaaaaa1aaaaaff1ffffffffffffff1fffffff1ffffffffffffff1fffff1ffffffffffffffffff11111111111aaaaaaffffffffffffff1ffffff1ff11ffffffffffffffffff1
fffffffffffff1ffaaaaaaaaaaaaaaaaaaa1ffffffffffffff1fffffff1ffffffffffffff1fffff1ffffffffffffffffff1aaaaaaaaaaaaaaaaaaffffffffffff1ffffff1ffff11fffffffffffffff1f
fffffffffffff1ffaaaaaaaaaaaa1aaaaaa1ffffffffffffff1fffffff1ffffffffffffff1fffff1ffffffffff1fffffff1aaaaaaaaaaaaaaaaaaaf11ffffffff1fffffffffffff1ffffffffffffff1f
fffffffffffff1fffaaaaaaaaaa1aaaaaaa1fffaafffffffff1fffffff1ffffffffffffff1fffff1fffffffff11fffffff1aaaaaaaaaaaaaaaaaaaf11aaffffff1ffffffffffffff11ffffffffffff1f
fffffffffffff1aaa9aaaaaaaaa1aaaaaaa1ffaaaaafffffff1fffffff1ffffffffffffff1fffff1fffffffff1fffffaaa19aaaaaaaaaaaaaaaaaaf11aaaaffff1ffffffffffffffffffffffffffff1f
ffffffffffffa1aaaa9aaaaaaaa1aaaaaaa1ffaaaaafffffff11ffffff1ffffffffffffff1fffff1fffffffff1ffffaaaa1aaaaaaaaaaaaaaaaaaff11aaaaffff1fffffffffffffffffffffffffff1ff
ffffffffffffa1aaaaaaaaaaaaa1aaaaaa91aaaaaaaaffffff1fffffff1ffffffffffffff1fffff1fffffffff1ffffaaaa1aaaaaaaaaaaaaaaaa9a111aaaaafff1fffffffffffffffffffffffffff1ff
ffffffffffffa1aaaaaaaaaaaaa1aaaaaaa1faaaaaaaffffff1fffffff1ffffffffffffff1fffff1ffffffff11ffffaaaa1aaaaaaaaaaaaaaaaaaa1a1aaaaafff1fffffffffffffffffffffffffff1ff
fffffffffffff1aaaaaaaaaaaa1aaaafffa1aaaaaaaaffffff1fffffff1ffffffffffffff1fffff1ffffffff1ffffffaaa1aaaaaaaaaaaaaaaaaaa1a1aaaaafff1fffffffffffffffffffffffffff1ff
ffaaaffffaaaa1aaaaaaaaaaaa1aaaafaaa11111111111111111ffffff1faaaafffffffff1fffff1ffffaa11fffaaaa9aa1aaaaaaaaaaaaaaaaaaa1a1aaaaffaa1ffffffffffffaaaafffffffffff1ff
faaaaaffaaaaa1aaaaaaaaaaaa1aaaafaaa1afaaaaafaaaaffffffffff1aaaaaaffffffff1fffff1fffaa11affaaaaaaaa1aaaaaaaaaaaaaaaaaaa1a11aaafaaa1fffffffffffaaaaaafffffffff1fff
faaaaafaaaaaa1aaaaaaaaaaaa1aaaaaaaa1aafaaaaaaaaaffffffffff1aaaaaafaafffff1fffff1fff11aaafaaaaaaaaa1aaaaaaaaaaaaaaaaaa1aaa1aaafaa11fffffffffffaaaaaafaaafffff1fff
ffaaaaaaaaaaa1aaaaaaaaaffa1aaaafaaa1aaafaaaaaaaaffffffffff1ffaaaaaaaaffff1fffff1ff1faaaaaaaaaaaaaa1aaaafffaaaaaaaaafafaaa1aaaaaa1afffffffffffffaaaaaaaaaffff1fff
faaaaaaaaaaaa1aaaaaaaffff11aaaaffaa1aaa1faaaaaafffffffffaa1afaaaaaaaaffff1fffff1f1faaaaaaaaaaaaaaa1aaafaaffaaaaaaaffafaaa1aaaaaa1fffffffffaaaafaaaaaaaaafff1ffff
aaaaaaaaaaaaa1aaa111ffaaffaaaaaafaa1aaaaffaaaaaafffffffaaa1afaaaaaaaaffff1fffff11faaaaaaaaaaaaaaaa11ff1111f11aaaaafaa1faaa1aaaaa1afffffffaaaaaaaaaaaaaaffff1ffff
aaaaaaaaaaaaa1aa11aafaaaafaaaaaaafa1aaaaafaaaaaaafaaaffaaa1afaaaaaaaaafaa1fffff11111aaaaaaaaabaaaa11f11111ff1aaaaaaaa1aafa1aaaaa1aafaaaffaaaaaaaaaaaaaaaaa1fffff
aaaaaaaaaaaaa1aaaa11f1aaaffaaaaaaaf1aaaaafaaaaaaaaaaaaaaaa1aafaaaaaaaafaa1ffff11bbaff1faaaabbbaaaa1aaaaaaaafaaaaaafaaffffffffffffffaaaaaaaaaaaaaaaaaaaaaaa1affff
aaaaaaaaaaaaa1aaaaaafa111afaaaaaaaf1aaaaaa1aaaaaaaaaaaaaaa1aaafaaaaaaaaaa1fffbb1ffffaa1faabbbbbaaa1aaaaaaaaffaaaaaffa1aaaaa1aaaa1aafaaaaaaaaaaaaaaaaaaaaaa1affff
aaaaaaaaaaaaa1aaaaaafaaaa11ffaaaaaa1aaaaabb1bbbbbbaaaaaaaa1aaaafaaaaaaaaa1aaabbfbbbbaaa1ffbbbbbaaa1aaaaaaaaafaaaaaafa1aaaaa1aaaa1fffaaaaabbbbbbbbbbaaaaaa1aaaaaa
aaaaaaaaaaaaa1aaaaaffaaaaaa1fffaaaa1aaaaabb1bbbbbbaaaaaaaa1aaaaaaaaaaaaaa1aaabf1bbbbaaaa1ffbbbbaaa1aaaaaaaaafaaaaaaaf1aaaaa1aaafffaaaaaaabbbbbbbbbbaaaaaa1aaaaaa
aaaaaaaaaaaaa1aaaaafbbaaaaa1aaafaaa1aaaaab111bbbbbaaaaaaaa1aaaaaaaaaaaaaa1ffabffbbbbaaaa11ffbbbbaafaaaaaaaaafaaaaaaafbaaaaa1ffff1aaaaaaaabb1b1bbbbbaaaaaa1aaaaaa
2aaaaaaaaaaaa1aaaaffbbbaaaaa1aaafff1aaaaabbbf1bb1baaaaaaaa1aaaaaaaaaaafffffaabbfbbbbaaaaa1bffbbbaafaaaaaaaaaaaaaaaab1bbaaaaa1aaa1aaaaaaaabbbbbf11bbaaaaa1aaaaaaa
2aaaaaaaaaaaa1aaaffbbbbaaaaa1aaaaaffaaaaabbbbfbbbbaaaaaaaa1abaaaaaaaabbbb1ffab11fbbbaaaaab1bfbbbaffaaaaaaaaafaaaabbbfbbfaaaa1aaa1aaaaaaaabbbffbbbbbaaaaa1aaaaaaa
2aaaaaaaaaaaa1aaffbb1baaaaaabaaaaaaffaaaabbbbf1bbbaaaaaaaa1bbaaaaaaaabbbffaffbb1ffbbaaaaab11bbbbaf1aaaaaaaafaaaaabbf1baafaaa1baa1aaaaaaaabbfb1bbbbbaaaaa1aabbaaa
2aaaaaaaaaaaa1ffabbbbbbaaaaab1aaaaf1faaaabbbbff11baaaaaaaa1bbaaaaaaaabbbbfaaffb1bfbbaaaaabb1bbbbff1aaaaaaafaaaaaabbfbbbaafaab1aa1aaaaaaaaffbbbbb1bbaaaaa1aabbaaa
2aaaaaaabbbaffaaabb11baaaaab1baaafa1faaaabbbbbf1bbaabbbbbb1bfafaaaaaabbbbffaabffffbbaaaaabb1fffffa1aaaaaaffaaaaaabbf1baaaafbb1aa1aaaaaaaffbbbbbbbbbabbb1bbbbbaaa
2abbaaaabbbff1bbbbb1bbbaaabb1bbaafa1faaaabbbbbff1baab11bbb1ffaaffaaaaabb11faabffbbbbaaabbbbfffbfbb1baaaabfbbbbbbbbffb1baaafff1b1aaaaaaaffbbbbbb11bbab111bbbbbaaa
2bbbaaaaab1fb1bbbbbbbbbaaab1bbbffaa1aaaaabbbbbbfb1aabbbb1b1fbaaafaaaabbbb1ffabb1bbbbaaabbbff1fbbbb1baaaabf1bbbbbbbf1bbbaaaabfffffffffffaabbbbbbbbbbabbb11bbbbaaa
2b12aaaaabbf1111bbbbbbbaaa1bbbbfaaa1aaaaabbbbbbbf1aabbbb1b1bbaaaaaaaabbbb1bfabb1bbbbaaabbbbf1fbbbb1111111f11111bbb1bbbbaaaabb111aaaaaaaaabbbbbbbbbbabb1b1bbffaaa
2222aaaabbbff1bbbfffffbbaa1bbbfbaab1abbabbbbbbbbfb1ab11bbb1bbaaaaafaabbbb1bfabb1bbbbaaabbbbb1fbbbbb111111f11111bffbbbbbbaabbbbbbaaabaafbbbbbbbbbbbbab11bbbffbaaa
b222aaaabbbbf1bbffbbbbfbaabbbbfbaab1bbbbbbbbbbbbffb11bbbbb1bbaabaabfabbbb1bfabb1bbbbaaabbbbb1fbbbbbbaaaabfbbbffffbbbbbbbaabbbbbbaaabbfbbbbfbbbbbbbbabb1bbbffbaaa
b2b2babb1fffffff1111111f11bbbbffbaffbb11bbbbbbbbbbbbb11bbfb111111111f1111bbfabb1bbbbaaabbbbbffbbbbbbbbabbb1fffbbbbbbbbbbaabbbbbbbaaabf1bbbfbbbbbbbbbb11bbfffbabb
b2bb2affffbbbbbbbbbbbbbfbb1bbbbffab1bbbbbbbbbbbbbbbbbbbfffbbbbbbabbbffbbbbbaabbbbbbbaaabbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbabbfbbbbfbbbbfbbbbbb1bbbfffbabb
b2bb2abfbfbbbbbbbbbbbbbbfbbbbbbbbabbbbbbbbbbbbbbbbbbbbffbbbbbbbbbbbbbbfbffffbbbbbbbbaaabbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbabfbbbbfbbbbbfbbbbbb1bbbfffbbbb
12bbb2bfbfbbbbbbbbbbbbbbfbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbabfbbbfbbbbbfbbbbbbb1bbbffffbbf
b2bbb2bbfbfbbbbbbbbbbbbbffbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbfbbbbfbbbbbbb1bbbbfbffffb
bb2bb2fbbfbfbbbbbbbbbbbbbfbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbabbbbfbbbbbfbbbbbbb1bbbbffffbbb
bb22bb2fbfbbfbbbbbbffbbbbffbbbbbbabb11111111111111111bbbbbbbbb1ffbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbbbbbbbbdbdbbbbbbbbbbbbbbbbbbbbbbbabbbbbbbbbfbbbbbbb1bbbbbbffff1b
bb22bb2fbfbbdfbbbbbbbbbbbbfbbbbbbabb11111111111111111bbb1111111ffff11bbbbbbbbbbb1bbbbbabbbbbbbbbbbbbbbbbbbbdd11111111111bbbbbbbbbabbbbbbbbfbbbbbbbb1bbbbbbbffffb
bb2b2bb2fbfbbbfbbbbbbbbbbbffbbbbbbbbbbbbbbd111bbbbbbbbbb1111111f11ff1bb1bbbbbbb1b1bbbbabbbbbb11111111111bbbb1bbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbdbbbbb1bbbbbbbbfbfb
bb2b21b2bfbfbbbfbbbbbbbbbbbfbbbbbbbbbbbbbbb111bbbbbbbbbb1bbbbb1fbffbbbbbbbbbbbb1d1bbbbbbbbbb1bbbbbbbbbbb1dbb1bbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbdbbbb1bbbbbbbbbfffb
bb2b2b1b2fbbfbbbfbbbbbbbbbbbfbbbbbbbbbbbbbb111bbbbbbbbbb1bbbbb11ffbbbbbbbbbbbbb1b1bbbbbbbbbb1bbbbbbbbbbb1bbb1bbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbb1bbbbbbbbbbfff
bb2b2b1b2bfbffbbfbbbbbbbbbbbfffbbbbbbbbbbbb111bbbbbbbbbb1bbbbbbffbbbbbb1bbbbbb1bdb1bbbbbbbbb1bbbbbbbbbbb1bbb1bbbbbbbbbbbbbbbbbbbbbbbbbbffbbbbdbbbb1bbbbbbbbbbbff
bb2b2bb12bbfdfbbfddbbbbbbbbbbbbffbbbdbbbbbb111bbbbbbbbbb1bbbbbbfbbbbbbbbbbbbbb1bbd1bbbbbbbbb1bbbbbbbbbbb1bffffbbbddbbbbbbbbbbbbbbbbbbbbfbbbbbbbbb1bbbbbbbbbbbbbf
bb2b2bb12bbfbfbbbfbbdbbbbbbbbbbbbfbbbbbbbbb111bbbbbbbbbb1bbbbbfbbbbbbbdbbbdbbb1bbbb1bbbbbbbb1bbbbbbbbbbb1fbb1bffbbbbdbbbbbbbbbbbbbbbbffbbbbbbbdbb1bbbbbbbbbbbbbf
bbbb2bbb2bbbfbbbbbfbdbbbbbbbbbbbbbffbbbbbbb111bbbbbbbbbb1bbbbbfbbbbbbbbbdbddb1bbbbb1bbbbbbbb1bbbbbbbbbbb1fbbbb11ffbbdbbbbbbbbbbbbbbbbfbbbbbbbbbbb1bbbbbbbbbbbbbf
bbb2bbbb21bbbfbbbdfbbbbbbbbbbbbbbbbfbbbbbbbffffbbbbbbbbb1bbbffbbbbbbbbbbbbbbb1bbbbb1bbbbbbbb1bbbbbbbbbbb1fbbbbbb11ffbbbbbbbbbbbbbbbbbfbbbbbbbbbb1bbbbbbbbbbbbbbb
bbb2bbb221bbbbfbbbbbbbbbbbbbbbbbbbbfbbbbbbbf11fbbbbbbbbb1bbbfbdbbbbbbbbbbbbbb1bbbbbb1bbbbbbb1bbbfffbbbbb1fbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbb
bbd2bbbbbb1bbbbfbddddbbbbbbbbbbbbbbbfbbbbbff11bbbbbbbbbb1bbffbbbbbbbbbdbbbbb1bbbbbbb1bbbbbbb1111f11f1111ffbbbbbbbddbfbbffbbbbbbbbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbb
bbbbbbbbbbb1bbbbbbbbbbbbbbbbbbbbbbbbfbbbbff111bbbbbbbbbb1bffbbbfbbbbbbbbbbbfffffbbbb1bbbbbbb1b1ffbbbfbbffbbbbbbbbbbbbfb1bffbbbbbbbbbbbbbbbbbbbd1bbbbbbbbbbbbbbbb
bbbbbbbbbbb1bbbbbbbbbbbbbbbbbbbbbbbbfbbbbfb11fbbbbbbbbbb11f111ff11111bbbbff1bbbffbbbb1bbbbbb1bbfbbbbffffbbbbbbbbbbbbbbb1bbbffbbbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbbb
bbbbbbbbbbbb1bbfffbbbbbbbbbbbbbbbbbbffbbbfb1f1bbbbbbbbbb1ff1111111111bbbffb1bbbbff11111bbbbfffff1bbbbbbbbbbbbbbbbbbbbbb1bbbbbffbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbbb
bbbbbbbbbbbffffbbbbbbbbbbbbbbbbbbbbbbfbbbfb1f1bbbbbbbbbb1fbbbffbbbbbbbbbfbb1b11111bbbb1bbbfb1bbbb1bbbbbbbbbbbbbbbbbbbbb1bbbbbbdfffbbbbbbbbbbbb1bbbbbbbbbbbbbbbbb
bbbbbbbbbffbb1bbbbbbbbbbbbbbbbbbbbbbbffbbfb1f1bbbbbbbbbb1fbbbbfbbbbbbbbbbb1bbbbbbfbbbb1bbbff1bbbbb1bbbbbbbbbbbbbbbbbbbb1bbbbbbbbbbffbbbbbbbbbb1bbbbbbbbbffbbbbbb
bbbbbbbbbfbbb1bbbbbbbbbbbbdddbbbbbbbbbffffb1f1bbbbffffbbffbbbbffbbbbbbbbbb1bbbbbbffbbb1bbbbffbbbbbb1bbbbbbbbbbbbbbbbbbb1bddbdbdbbbbbffbbbbbbbb1bbbbbbbbbbffbbbbb
bbbbbbbbbbbbbb1bbbbbbbbbbbbddbbbbbbbbbbbbbb11ffbbfbbbffffbbbbbbfbbbbbbbbbb1bbbbbbbbfffb1bbbbfbbbbbbb1bbbbbbbbbbbfbbbbbbfbbbbdbdbbbbbbbffbbbbb1bbbbbbbbbbbbfbbbbb
bbbbbbbbbbbbbb1bbbbbbbbbbbbbbbbbbbbdbbbbbbb111bffbbbbbfb1bbbbbbbbbbbbbbbb1bbbbbbbbbbbbb1bbbbfbbbbbbbb1bbbbbbbbbbfbbbbbbf1bbbbbdbbbbdbbbbfffffffbbbbbbbbbbbbfbbbb
bbbbbbbbbbbbbbb1bbbbbbbbbbdbbbbbbbbbbbbbbbb111bbbbbbbbbb1bbbbbbbbbbbbbbbb1bbbbbbbbbbbbbb1bbbfbbbbbbbbb1bbbbbbbbbffbb111fbbdbbbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbfbbbb
bbbbbbbbbbbbbbbb1bbbbbbbbbdddbbbbbbbbbbbbbb111bbbbbbbbbb1bbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbffbffbbbbbbbbbb1bbbbbbbb1f11bbbfbddbdbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbfbbbb
bbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbbbbbdbbbbbbb111bbbbbbbbbb1bbbbbbbbbbbbbbb1bbbbbbbbbbbbbbb1ffb1bbbbbbbbbbb1bbbb111bbfbbbbbbbbbbbbbbbbbbbbbbbbb1bbbbbbbbbbbbbbfbbbb
bbbbbbbfbbbbbbbbb1bbbbbbbbbbbbbbbbfbbbbbbbb111bbbbbbbbbb1111111111111bbb1bfbbbbbbbbbbbbbb1bb1bbbbfbbbbbbb1bbbbbbbbffbbbbbbbbbbbbbbbbbbbbbfbb1bbbbbbbbbbbbbffbbbb
bbbbbbfbfbffbbbbb1fbbbbfbbbfbbbbfbffbbbfbbb111fbbbffbbbb1111111111111bbb1bffbbbfbbbbbbfbbbffbbbbbffbbbbfbbbfbbbbfbffffffbbbbbbfbbbffbbbbbff1bbbfbbbfbbbbfbfffbbf
bbfbbbffbffbbfbbbf1bbbffbbbffbbbfbbffbffbbfbbbffbffbbfbbbffbbbffbbbffbbbfbbffbffbbfbbbffbffbbfbbbffbbbffbbbffbbbfbbffbffbbfbbbffbffbbfbbbff1bbffbbbffbbbfbbffbff
bbffbbffbffbbffbbbf1bffbbbbffbfbffbffffbbbffbbffbffbbffbbbffbffbbbbffbfbffbffffbbbffbbffbffbbffbbbffbffbbbbffbfbffbffffbbbffbbffbffbbffbbbf1bffbbbbffbfbffbffffb
fffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
ffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
fffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image2":
            case "teary knight":return img`
. . . . . . b f f b . . . . . . 
. . . . 2 b f f f f b b . . . . 
. . . b f b b b b b b b b . . . 
. . f b b f f f f f f b b f . . 
. . f b f f f f f f f f b f . . 
. . b b f b b b b b b f b b . . 
. . b f b b b b b b b b f b . . 
. b f b b b 2 b b 2 b b b f b . 
. b b b b 1 2 d d 2 1 b b b b . 
. . f b b 8 d d d 8 d b b f . . 
. . . f b b 8 b b b 8 b f . . . 
. . e b f 8 b b b 8 b f b e . . 
. . b d f f 8 f f f 8 f d b . . 
. . b b f 8 b f f 8 b f b b . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Start":
            case "anim1":return [img`
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffff1fffffffffffffffffff1111fffffff
fffff111fffff1fffff11ffffff111ff1111fff1ff1fffffff
fffff1fffffff1fffff11fffff1ff1ffff1ffffff11ff1ffff
fffff1ffff1ff1fffff1f1ffff1ff1ffff1ffffff1fff11fff
fffff1fffff11ffffff1f1ffff1111ffff1fffff11fff111ff
ffffff11ffff111ffff1f1ffff11ffffff1ffffffffff1111f
fffffff1ffff1ffffff1111fff111fffff1fffff1ffff111ff
ffffffff1fff1ffffff1ff1fff1ff1fffffffffffffff11fff
fffffff11fff1ffffff1ff1fff1fffffffffffffffffffffff
ffffff11ffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
`, img`
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
`, img`
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffff1fffffffffffffffffff1111fffffff
fffff111fffff1fffff11ffffff111ff1111fff1ff1fffffff
fffff1fffffff1fffff11fffff1ff1ffff1ffffff11ff1ffff
fffff1ffff1ff1fffff1f1ffff1ff1ffff1ffffff1fff11fff
fffff1fffff11ffffff1f1ffff1111ffff1fffff11fff111ff
ffffff11ffff111ffff1f1ffff11ffffff1ffffffffff1111f
fffffff1ffff1ffffff1111fff111fffff1fffff1ffff111ff
ffffffff1fff1ffffff1ff1fff1ff1fffffffffffffff11fff
fffffff11fff1ffffff1ff1fff1fffffffffffffffffffffff
ffffff11ffff1fffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
`, img`
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff
`];
            case "sword":
            case "anim2":return [img`
.........................
........11...............
.....11111...............
....1ddddd1..............
.....dfdfd...............
.....ddddd...............
.....ddddd...............
......ddd................
....ffdddff...ff.........
....dfffffd..f2f.........
....dfffffd.f22f.........
....dfffffdf25f..........
....fffffff252f..........
.....ffffff22f...........
.....88.88.ff............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11...............
.....11111...............
....1ddddd1..............
.....dfdfd...............
.....ddddd...............
.....ddddd....ff.........
......ddd....f2f.........
....ffdddff.f22f.........
....dfffffdf25f..........
....dffffff252f..........
....dffffff22f...........
....ffffff.ff............
.....fffff...............
.....88.88...............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11...............
.....11111...............
....1ddddd1...ff.........
.....dfdfd...f2f.........
.....ddddd..f22f.........
.....ddddd.f25f..........
......ddd.f252f..........
....ffdddfd22f...........
....dffffffff............
....dffffff..............
....dffffff..............
....ffffff...............
.....fffff...............
.....88.88...............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11.....ff........
.....11111....f2f........
....1ddddd1..f22f........
.....dfdfd..f252f........
.....ddddd.f252ff........
.....ddddd.f25f..........
......ddd.f252f..........
....ffdddfd22f...........
....dffffffff............
....dffffff..............
....dffffff..............
....ffffff...............
.....fffff...............
.....88.88...............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11...............
.....11111...............
....1ddddd1..............
.....dfdfd...............
.....ddddd...............
.....ddddd.......ff......
......ddd......ff2f......
....ffdddff.fff222f......
....dfffffdf22555f.......
....dffffff2522fff.......
....dffffff22fff.........
....ffffff.ff............
.....fffff...............
.....88.88...............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11...............
.....11111...............
....1ddddd1..............
.....dfdfd...............
.....ddddd...............
.....ddddd...............
......ddd........ff......
....ffdddff.....f2f......
....dfffffd....f22f......
....dfffffd..ff25f.......
....dfffffddff252f.......
....ffffffdd2252f........
.....fffffffffff.........
.....88.88...............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`, img`
.........................
........11...............
.....11111...............
....1ddddd1..............
.....dfdfd...............
.....ddddd...............
.....ddddd...............
......ddd................
....ffdddff...ff.........
....dfffffd..f2f.........
....dfffffd.f22f.........
....dfffffdf25f..........
....fffffff252f..........
.....ffffff22f...........
.....88.88.ff............
.....88.88...............
.....88.88...............
.....88.88...............
.....ff.ff...............
.........................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
